plugins:
  - jekyll-feed
  - jekyll-sitemap

#SEO Stuff
author: Alen Karnil
description: This is my website i guess
lang: en
locale: en_GB
url: "https://datapaganism.github.io"
baseurl: ""


# OPTIONAL: override baseurl and url if using a custom domain
# Note: leave out the trailing / from this value. 
#url: "https://fastpages.fast.ai" # the base hostname & protocol for your site, e.g. http://example.com

#RSS feeds
feed:
  posts_limit: 20